//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBanque2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="ServiceReference1.BanqueWs")]
    public interface BanqueWs {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWs/ConversionEuroToDhRequest", ReplyAction="http://service/BanqueWs/ConversionEuroToDhResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBanque2.ServiceReference1.ConversionEuroToDhResponse ConversionEuroToDh(ClientBanque2.ServiceReference1.ConversionEuroToDhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWs/ConversionEuroToDhRequest", ReplyAction="http://service/BanqueWs/ConversionEuroToDhResponse")]
        System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.ConversionEuroToDhResponse> ConversionEuroToDhAsync(ClientBanque2.ServiceReference1.ConversionEuroToDhRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWs/getcompteRequest", ReplyAction="http://service/BanqueWs/getcompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBanque2.ServiceReference1.getcompteResponse getcompte(ClientBanque2.ServiceReference1.getcompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWs/getcompteRequest", ReplyAction="http://service/BanqueWs/getcompteResponse")]
        System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.getcompteResponse> getcompteAsync(ClientBanque2.ServiceReference1.getcompteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWs/getComptesRequest", ReplyAction="http://service/BanqueWs/getComptesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientBanque2.ServiceReference1.getComptesResponse getComptes(ClientBanque2.ServiceReference1.getComptesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service/BanqueWs/getComptesRequest", ReplyAction="http://service/BanqueWs/getComptesResponse")]
        System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.getComptesResponse> getComptesAsync(ClientBanque2.ServiceReference1.getComptesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDh", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class ConversionEuroToDhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double monatant;
        
        public ConversionEuroToDhRequest() {
        }
        
        public ConversionEuroToDhRequest(double monatant) {
            this.monatant = monatant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDhResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class ConversionEuroToDhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConversionEuroToDhResponse() {
        }
        
        public ConversionEuroToDhResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private System.DateTime datecreationField;
        
        private bool datecreationFieldSpecified;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime datecreation {
            get {
                return this.datecreationField;
            }
            set {
                this.datecreationField = value;
                this.RaisePropertyChanged("datecreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datecreationSpecified {
            get {
                return this.datecreationFieldSpecified;
            }
            set {
                this.datecreationFieldSpecified = value;
                this.RaisePropertyChanged("datecreationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getcompte", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getcompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public getcompteRequest() {
        }
        
        public getcompteRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getcompteResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getcompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBanque2.ServiceReference1.compte @return;
        
        public getcompteResponse() {
        }
        
        public getcompteResponse(ClientBanque2.ServiceReference1.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptes", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getComptesRequest {
        
        public getComptesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getComptesResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class getComptesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientBanque2.ServiceReference1.compte[] @return;
        
        public getComptesResponse() {
        }
        
        public getComptesResponse(ClientBanque2.ServiceReference1.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueWsChannel : ClientBanque2.ServiceReference1.BanqueWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueWsClient : System.ServiceModel.ClientBase<ClientBanque2.ServiceReference1.BanqueWs>, ClientBanque2.ServiceReference1.BanqueWs {
        
        public BanqueWsClient() {
        }
        
        public BanqueWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBanque2.ServiceReference1.ConversionEuroToDhResponse ClientBanque2.ServiceReference1.BanqueWs.ConversionEuroToDh(ClientBanque2.ServiceReference1.ConversionEuroToDhRequest request) {
            return base.Channel.ConversionEuroToDh(request);
        }
        
        public double ConversionEuroToDh(double monatant) {
            ClientBanque2.ServiceReference1.ConversionEuroToDhRequest inValue = new ClientBanque2.ServiceReference1.ConversionEuroToDhRequest();
            inValue.monatant = monatant;
            ClientBanque2.ServiceReference1.ConversionEuroToDhResponse retVal = ((ClientBanque2.ServiceReference1.BanqueWs)(this)).ConversionEuroToDh(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.ConversionEuroToDhResponse> ClientBanque2.ServiceReference1.BanqueWs.ConversionEuroToDhAsync(ClientBanque2.ServiceReference1.ConversionEuroToDhRequest request) {
            return base.Channel.ConversionEuroToDhAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.ConversionEuroToDhResponse> ConversionEuroToDhAsync(double monatant) {
            ClientBanque2.ServiceReference1.ConversionEuroToDhRequest inValue = new ClientBanque2.ServiceReference1.ConversionEuroToDhRequest();
            inValue.monatant = monatant;
            return ((ClientBanque2.ServiceReference1.BanqueWs)(this)).ConversionEuroToDhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBanque2.ServiceReference1.getcompteResponse ClientBanque2.ServiceReference1.BanqueWs.getcompte(ClientBanque2.ServiceReference1.getcompteRequest request) {
            return base.Channel.getcompte(request);
        }
        
        public ClientBanque2.ServiceReference1.compte getcompte(long arg0) {
            ClientBanque2.ServiceReference1.getcompteRequest inValue = new ClientBanque2.ServiceReference1.getcompteRequest();
            inValue.arg0 = arg0;
            ClientBanque2.ServiceReference1.getcompteResponse retVal = ((ClientBanque2.ServiceReference1.BanqueWs)(this)).getcompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.getcompteResponse> ClientBanque2.ServiceReference1.BanqueWs.getcompteAsync(ClientBanque2.ServiceReference1.getcompteRequest request) {
            return base.Channel.getcompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.getcompteResponse> getcompteAsync(long arg0) {
            ClientBanque2.ServiceReference1.getcompteRequest inValue = new ClientBanque2.ServiceReference1.getcompteRequest();
            inValue.arg0 = arg0;
            return ((ClientBanque2.ServiceReference1.BanqueWs)(this)).getcompteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientBanque2.ServiceReference1.getComptesResponse ClientBanque2.ServiceReference1.BanqueWs.getComptes(ClientBanque2.ServiceReference1.getComptesRequest request) {
            return base.Channel.getComptes(request);
        }
        
        public ClientBanque2.ServiceReference1.compte[] getComptes() {
            ClientBanque2.ServiceReference1.getComptesRequest inValue = new ClientBanque2.ServiceReference1.getComptesRequest();
            ClientBanque2.ServiceReference1.getComptesResponse retVal = ((ClientBanque2.ServiceReference1.BanqueWs)(this)).getComptes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.getComptesResponse> ClientBanque2.ServiceReference1.BanqueWs.getComptesAsync(ClientBanque2.ServiceReference1.getComptesRequest request) {
            return base.Channel.getComptesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientBanque2.ServiceReference1.getComptesResponse> getComptesAsync() {
            ClientBanque2.ServiceReference1.getComptesRequest inValue = new ClientBanque2.ServiceReference1.getComptesRequest();
            return ((ClientBanque2.ServiceReference1.BanqueWs)(this)).getComptesAsync(inValue);
        }
    }
}
